export const APP_START = "APP_START";
export const APP_STOP = "APP_STOP";

export const ROOT_CHANGED = "ROOT_CHANGED";

export const NETWORK_GOES_ONLINE = "NETWORK_GOES_ONLINE";
export const NETWORK_GOES_OFFLINE = "NETWORK_GOES_OFFLINE";

export const APPSTATE_GOES_FRONT = "APPSTATE_GOES_FRONT";
export const APPSTATE_GOES_BACK = "APPSTATE_GOES_BACK";



export const LOCATION_GET_REQUEST = "LOCATION_GET_REQUEST";
export const LOCATION_GET_REQUEST_SUCCESSFUL = "LOCATION_GET_REQUEST_SUCCESSFUL";
export const LOCATION_GET_REQUEST_FAILED = "LOCATION_GET_REQUEST_FAILED";

export const LOCATION_WATCH_START = "LOCATION_WATCH_START";
export const LOCATION_WATCH_START_SUCCESSFUL = "LOCATION_WATCH_START_SUCCESSFUL";
export const LOCATION_WATCH_START_FAILED = "LOCATION_WATCH_START_FAILED";

export const LOCATION_WATCH_UPDATE_SUCCESSFUL = "LOCATION_WATCH_UPDATE_SUCCESSFUL";
export const LOCATION_WATCH_UPDATE_FAILED = "LOCATION_WATCH_UPDATE_FAILED";

export const LOCATION_WATCH_STOP = "LOCATION_WATCH_STOP";
export const LOCATION_WATCH_STOP_SUCCESSFUL = "LOCATION_WATCH_STOP_SUCCESSFUL";
export const LOCATION_WATCH_STOP_FAILED = "LOCATION_WATCH_STOP_FAILED";

export const LOCATION_UPDATE_SUBMIT = "LOCATION_UPDATE_SUBMIT";
export const LOCATION_UPDATE_SUBMITTING = "LOCATION_UPDATE_SUBMITTING";
export const LOCATION_UPDATE_SUBMIT_SUCCESSFUL = "LOCATION_UPDATE_SUBMIT_SUCCESSFUL";
export const LOCATION_UPDATE_SUBMIT_FAILED = "LOCATION_UPDATE_SUBMIT_FAILED";




export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUESTING = "USER_LOGIN_REQUESTING";
export const USER_LOGIN_REQUEST_SUCCESSFUL = "USER_LOGIN_REQUEST_SUCCESSFUL";
export const USER_LOGIN_REQUEST_FAILED = "USER_LOGIN_REQUEST_FAILED";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_REQUESTING = "USER_LOGOUT_REQUESTING";
export const USER_LOGOUT_REQUEST_SUCCESSFUL = "USER_LOGOUT_REQUEST_SUCCESSFUL";
export const USER_LOGOUT_REQUEST_FAILED = "USER_LOGOUT_REQUEST_FAILED";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_REQUESTING = "USER_UPDATE_REQUESTING";
export const USER_UPDATE_REQUEST_SUCCESSFUL = "USER_UPDATE_REQUEST_SUCCESSFUL";
export const USER_UPDATE_REQUEST_FAILED = "USER_UPDATE_REQUEST_FAILED";

export const USER_OPTIONS_LOAD_REQUEST = "USER_OPTIONS_LOAD_REQUEST";
export const USER_OPTIONS_LOAD_REQUESTING = "USER_OPTIONS_LOAD_REQUESTING";
export const USER_OPTIONS_LOAD_REQUEST_SUCCESSFUL = "USER_OPTIONS_LOAD_REQUEST_SUCCESSFUL";
export const USER_OPTIONS_LOAD_REQUEST_FAILED = "USER_OPTIONS_LOAD_REQUEST_FAILED";

export const USER_OPTIONS_SAVE_REQUEST = "USER_OPTIONS_SAVE_REQUEST";
export const USER_OPTIONS_SAVE_REQUESTING = "USER_OPTIONS_SAVE_REQUESTING";
export const USER_OPTIONS_SAVE_REQUEST_SUCCESSFUL = "USER_OPTIONS_SAVE_REQUEST_SUCCESSFUL";
export const USER_OPTIONS_SAVE_REQUEST_FAILED = "USER_OPTIONS_SAVE_REQUEST_FAILED";

export const SOCKET_START_REQUEST = "SOCKET_START_REQUEST";
export const SOCKET_START_REQUESTING = "SOCKET_START_REQUESTING";
export const SOCKET_START_REQUEST_SUCCESSFUL = "SOCKET_START_REQUEST_SUCCESSFUL";
export const SOCKET_START_REQUEST_FAILED = "SOCKET_START_REQUEST_FAILED";

export const SOCKET_STOP_REQUEST = "SOCKET_STOP_REQUEST";
export const SOCKET_STOP_REQUESTING = "SOCKET_STOP_REQUESTING";
export const SOCKET_STOP_REQUEST_SUCCESSFUL = "SOCKET_STOP_REQUEST_SUCCESSFUL";
export const SOCKET_STOP_REQUEST_FAILED = "SOCKET_STOP_REQUEST_FAILED";

export const SOCKET_SUBMIT_USERID = "SOCKET_SUBMIT_USERID";
export const SOCKET_SUBMITTING_USERID = "SOCKET_SUBMITTING_USERID";
export const SOCKET_SUBMIT_USERID_SUCCESSFUL = "SOCKET_SUBMIT_USERID_SUCCESSFUL";
export const SOCKET_SUBMIT_USERID_FAILED = "SOCKET_SUBMIT_USERID_FAILED";
